apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: api-route-rl-user1
  namespace: atp-user1
  labels:
    workshop.user: user1
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: api-route-user1
  limits:
    "per-user-per-minute":
      rates:
        - limit: 20
          window: 60s
      counters:
        - expression: auth.identity.user_id
